#################################
#       Batocera Settings       #
#################################

# Specify the backend to use: `xrender`, `glx`, or `egl`.
#
# Default: "xrender"
backend = "glx"

# Enable/disable VSync.
#
# Default: false
vsync = true;

