################################################################################
#
# yabasanshiro
#
################################################################################
# Version: 3.5.0 - Commits on Sep 28, 2022
YABASANSHIRO_VERSION = fd459968aae4a251d839174404a346b1f428912a
YABASANSHIRO_SITE = https://github.com/libretro/yabause
YABASANSHIRO_SITE_METHOD=git
YABASANSHIRO_GIT_SUBMODULES=YES
YABASANSHIRO_LICENSE = GPLv2
YABASANSHIRO_LICENSE_FILE = LICENSE
YABASANSHIRO_SUBDIR = yabause

YABASANSHIRO_DEPENDENCIES = sdl2 libcurl boost libglfw

YABASANSHIRO_CONF_ENV += LDFLAGS="$(TARGET_LDFLAGS) -L$(STAGING_DIR)/usr/lib -lpthread -ludev"

YABASANSHIRO_CONF_OPTS += -DCMAKE_BUILD_TYPE=Release
YABASANSHIRO_CONF_OPTS += -DCMAKE_SYSTEM_NAME=Linux
YABASANSHIRO_CONF_OPTS += -DCMAKE_INSTALL_PREFIX="/usr/bin/yabasanshiro"
YABASANSHIRO_CONF_OPTS += -DBUILD_SHARED_LIBS=OFF
YABASANSHIRO_CONF_OPTS += -DOpenGL_GL_PREFERENCE=GLVND
YABASANSHIRO_CONF_OPTS += -DYAB_PORTS=retro_arena
YABASANSHIRO_CONF_OPTS += -DYAB_WANT_OPENGL=ON
YABASANSHIRO_CONF_OPTS += -DYAB_WANT_SDL=ON
YABASANSHIRO_CONF_OPTS += -DYAB_WANT_OPENAL=OFF
YABASANSHIRO_CONF_OPTS += -DYAB_WANT_MUSASHI=ON
YABASANSHIRO_CONF_OPTS += -DYAB_WANT_C68K=FALSE
YABASANSHIRO_CONF_OPTS += -DSH2_DYNAREC=FALSE
YABASANSHIRO_CONF_OPTS += -DUSE_EGL=TRUE

ifeq ($(BR2_arm)$(BR2_aarch64),y)
    YABASANSHIRO_CONF_OPTS += -DYAB_WANT_DYNAREC_DEVMIYAX=ON
endif

ifeq ($(BR2_PACKAGE_BATOCERA_TARGET_BCM2711),y)
    YABASANSHIRO_CONF_DEFINITIONS += -D__RP64__ -D__RETORO_ARENA__
    YABASANSHIRO_CONF_DEFINITIONS += -D__RP64__ -D__RETORO_ARENA__
endif

ifeq ($(BR2_x86_64),y)
    YABASANSHIRO_CONF_OPTS += -DYAB_WANT_DYNAREC_DEVMIYAX=OFF
    YABASANSHIRO_CONF_DEFINITIONS += -D__PC__ -D__RETORO_ARENA__
    YABASANSHIRO_CONF_DEFINITIONS += -D__PC__ -D__RETORO_ARENA__
endif

ifeq ($(BR2_arm),y)
    YABASANSHIRO_CONF_OPTS += -DYAB_WANT_ARM7=ON
endif

YABASANSHIRO_CONF_OPTS += -DCMAKE_C_FLAGS="$(TARGET_CFLAGS) $(YABASANSHIRO_CONF_DEFINITIONS)"
YABASANSHIRO_CONF_OPTS += -DCMAKE_CXX_FLAGS="$(TARGET_CXXFLAGS) $(YABASANSHIRO_CONF_DEFINITIONS)"

define YABASANSHIRO_GIT_HASH
    sed -i 's/@GIT_SHA1@/$(shell echo "$(YABASANSHIRO_VERSION)" | cut -c1-7)/g' $(@D)/yabause/src/config.h.in
endef

define YABASANSHIRO_POST_PROCESS
	mkdir -p $(TARGET_DIR)/usr/share/evmapy
	cp -f $(BR2_EXTERNAL_BATOCERA_PATH)/package/batocera/emulators/yabasanshiro/saturn.yabasanshiro.keys \
        $(TARGET_DIR)/usr/share/evmapy
endef

YABASANSHIRO_PRE_CONFIGURE_HOOKS = YABASANSHIRO_GIT_HASH
YABASANSHIRO_POST_INSTALL_TARGET_HOOKS += YABASANSHIRO_POST_PROCESS

$(eval $(cmake-package))
